{
  "language": "swift",
  "os_image": "xcode8.3",
  "os": "osx",
  "xcode_project": "TimerTracker.xcodeproj",
  "xcode_scheme": "TimerTracker",
  "xcode_sdk": "iphonesimulator8.3",
  "before_install": [
    "gem install cocoapods --pre",
    "gem install xcpretty -N"
  ],
  "script": [
    "pod update",
    "set -o pipefail",
    "xcodebuild -workspace TimerTracker.xcworkspace -scheme TimerTracker -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c"
  ]
}
